### ISSUE TITLE
max lags output from LagReg with inverse=TRUE

### ISSUE THREAD

**Issue by farlies** [nickpoison/astsa#1]
In LagReg.R, the table of lags with large coefficients printed by the function LagReg, when argument `inverse=TRUE`, seems to list lag values _1 less than_ the actual lag.  For Example 4.24 in ASTSA, this prints
```
The negative lags, at which the coefficients are large
in absolute value, and the coefficients themselves, are: 
     lag s     beta(s)
[1,]     3  0.01593167
[2,]     4 -0.02120013
```

- The Betas are right, but it should print lags `s` 4 & 5, not 3 & 4.
- The generated plot shows the correct lags.
- This differs from what is printed in the ASTSA Edition 4, which also shows the _correct_ lags.
- The github version of this function (2f637b50db656781c7653a6b19b47a6bbb583ab2)  and the code  in CRAN package (1.8) exhibit the same behavior.
- A correct lag table is generated when the inverse argument defaults to FALSE

Possibly line 149 should be  `mat = cbind(sig.s, b.neg.sig)` ?

**Comment by nickpoison** [comment]
Fixed- thanks.  Don't know why this happened because the script hasn't changed since edition 3.
