### ISSUE TITLE
Error matrix singular

### ISSUE THREAD

**Issue by rnrpereira** [nickpoison/astsa#3]
Hi,
I am new in using astsa package.
And I wanted to compute the spectral envelop of a categrical time series of animal vocalizations I have.
However, I'm getting the following error.

`> u = specenv(xdata, section=1:892, spans=c(5,5))`
`Error in matrixpwr(A, power) : matrix singular`

I have used dna2vector to create the indicator vectors and it runs ok.
Creates the proper matrix of indvectors (no. rows =  time-series length; no cols = no. of categories)

I suppose the indicator matrix is singular and it is not possible to compute the eigenvalues/vectors.
Does anyone could explain me the reason for this error?

thanks a lot,
Rodrigo

**Comment by nickpoison** [comment]
I don't think this is a problem with `specenv` - my guess is that you have one category that has never been visited.  If that's not the case, try asking at stackoverflow (https://stackoverflow.com/questions/tagged/r) but you need a minimal reproducible example (https://stackoverflow.com/help/minimal-reproducible-example).
